apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todos-api
  annotations: {}
spec:
  rules:
    - host: todos.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todos-api
                port:
                  number: 80

